using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BibleVerseCard.Models
{
    public class Bible
    {
        public Book Genesis = new Book
        {
            BookName = "Genesis",
            VersesByChapter = new List<VersesByChapter>
            {
                {
                    1,31
                }
            }
            
                

        }

        public List<KeyValuePair<int, int>> Genesis1 = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,31),
            new KeyValuePair<int,int>(2,25),
            new KeyValuePair<int,int>(3,24),
            new KeyValuePair<int,int>(4,26),
            new KeyValuePair<int,int>(5,32),
            new KeyValuePair<int,int>(6,22),
            new KeyValuePair<int,int>(7,24),
            new KeyValuePair<int,int>(8,22),
            new KeyValuePair<int,int>(9,29),
            new KeyValuePair<int,int>(10,32),
            new KeyValuePair<int,int>(11,32),
            new KeyValuePair<int,int>(12,20),
            new KeyValuePair<int,int>(13,18),
            new KeyValuePair<int,int>(14,24),
            new KeyValuePair<int,int>(15,21),
            new KeyValuePair<int,int>(16,16),
            new KeyValuePair<int,int>(17,27),
            new KeyValuePair<int,int>(18,33),
            new KeyValuePair<int,int>(19,38),
            new KeyValuePair<int,int>(20,18),
            new KeyValuePair<int,int>(21,34),
            new KeyValuePair<int,int>(22,24),
            new KeyValuePair<int,int>(23,20),
            new KeyValuePair<int,int>(24,67),
            new KeyValuePair<int,int>(25,34),
            new KeyValuePair<int,int>(26,35),
            new KeyValuePair<int,int>(27,46),
            new KeyValuePair<int,int>(28,22),
            new KeyValuePair<int,int>(29,35),
            new KeyValuePair<int,int>(30,43),
            new KeyValuePair<int,int>(31,55),
            new KeyValuePair<int,int>(32,32),
            new KeyValuePair<int,int>(33,20),
            new KeyValuePair<int,int>(34,31),
            new KeyValuePair<int,int>(35,29),
            new KeyValuePair<int,int>(36,43),
            new KeyValuePair<int,int>(37,36),
            new KeyValuePair<int,int>(38,30),
            new KeyValuePair<int,int>(39,23),
            new KeyValuePair<int,int>(40,23),
            new KeyValuePair<int,int>(41,57),
            new KeyValuePair<int,int>(42,38),
            new KeyValuePair<int,int>(43,34),
            new KeyValuePair<int,int>(44,34),
            new KeyValuePair<int,int>(45,28),
            new KeyValuePair<int,int>(46,34),
            new KeyValuePair<int,int>(47,31),
            new KeyValuePair<int,int>(48,22),
            new KeyValuePair<int,int>(49,33),
            new KeyValuePair<int,int>(50,26),
        };

        public List<KeyValuePair<int, int>> Exodus = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,22),
            new KeyValuePair<int,int>(2,25),
            new KeyValuePair<int,int>(3,22),
            new KeyValuePair<int,int>(4,31),
            new KeyValuePair<int,int>(5,23),
            new KeyValuePair<int,int>(6,30),
            new KeyValuePair<int,int>(7,25),
            new KeyValuePair<int,int>(8,32),
            new KeyValuePair<int,int>(9,35),
            new KeyValuePair<int,int>(10,29),
            new KeyValuePair<int,int>(11,10),
            new KeyValuePair<int,int>(12,51),
            new KeyValuePair<int,int>(13,22),
            new KeyValuePair<int,int>(14,31),
            new KeyValuePair<int,int>(15,27),
            new KeyValuePair<int,int>(16,36),
            new KeyValuePair<int,int>(17,16),
            new KeyValuePair<int,int>(18,27),
            new KeyValuePair<int,int>(19,25),
            new KeyValuePair<int,int>(20,26),
            new KeyValuePair<int,int>(21,36),
            new KeyValuePair<int,int>(22,31),
            new KeyValuePair<int,int>(23,33),
            new KeyValuePair<int,int>(24,18),
            new KeyValuePair<int,int>(25,40),
            new KeyValuePair<int,int>(26,37),
            new KeyValuePair<int,int>(27,21),
            new KeyValuePair<int,int>(28,43),
            new KeyValuePair<int,int>(29,46),
            new KeyValuePair<int,int>(30,38),
            new KeyValuePair<int,int>(31,18),
            new KeyValuePair<int,int>(32,35),
            new KeyValuePair<int,int>(33,23),
            new KeyValuePair<int,int>(34,35),
            new KeyValuePair<int,int>(35,35),
            new KeyValuePair<int,int>(36,38),
            new KeyValuePair<int,int>(37,29),
            new KeyValuePair<int,int>(38,31),
            new KeyValuePair<int,int>(39,43),
            new KeyValuePair<int,int>(40,38),
        };

        public List<KeyValuePair<int, int>> Leviticus = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,17),
            new KeyValuePair<int,int>(2,16),
            new KeyValuePair<int,int>(3,17),
            new KeyValuePair<int,int>(4,35),
            new KeyValuePair<int,int>(5,19),
            new KeyValuePair<int,int>(6,30),
            new KeyValuePair<int,int>(7,38),
            new KeyValuePair<int,int>(8,36),
            new KeyValuePair<int,int>(9,24),
            new KeyValuePair<int,int>(10,20),
            new KeyValuePair<int,int>(11,47),
            new KeyValuePair<int,int>(12,8),
            new KeyValuePair<int,int>(13,59),
            new KeyValuePair<int,int>(14,57),
            new KeyValuePair<int,int>(15,33),
            new KeyValuePair<int,int>(16,34),
            new KeyValuePair<int,int>(17,16),
            new KeyValuePair<int,int>(18,30),
            new KeyValuePair<int,int>(19,37),
            new KeyValuePair<int,int>(20,27),
            new KeyValuePair<int,int>(21,24),
            new KeyValuePair<int,int>(22,33),
            new KeyValuePair<int,int>(23,44),
            new KeyValuePair<int,int>(24,23),
            new KeyValuePair<int,int>(25,55),
            new KeyValuePair<int,int>(26,46),
            new KeyValuePair<int,int>(27,34),
        };

        public List<KeyValuePair<int, int>> Numbers = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,54),
            new KeyValuePair<int,int>(2,34),
            new KeyValuePair<int,int>(3,51),
            new KeyValuePair<int,int>(4,49),
            new KeyValuePair<int,int>(5,31),
            new KeyValuePair<int,int>(6,27),
            new KeyValuePair<int,int>(7,89),
            new KeyValuePair<int,int>(8,26),
            new KeyValuePair<int,int>(9,23),
            new KeyValuePair<int,int>(10,36),
            new KeyValuePair<int,int>(11,35),
            new KeyValuePair<int,int>(12,16),
            new KeyValuePair<int,int>(13,33),
            new KeyValuePair<int,int>(14,45),
            new KeyValuePair<int,int>(15,41),
            new KeyValuePair<int,int>(16,50),
            new KeyValuePair<int,int>(17,13),
            new KeyValuePair<int,int>(18,32),
            new KeyValuePair<int,int>(19,22),
            new KeyValuePair<int,int>(20,29),
            new KeyValuePair<int,int>(21,35),
            new KeyValuePair<int,int>(22,41),
            new KeyValuePair<int,int>(23,30),
            new KeyValuePair<int,int>(24,25),
            new KeyValuePair<int,int>(25,18),
            new KeyValuePair<int,int>(26,65),
            new KeyValuePair<int,int>(27,23),
            new KeyValuePair<int,int>(28,31),
            new KeyValuePair<int,int>(29,40),
            new KeyValuePair<int,int>(30,16),
            new KeyValuePair<int,int>(31,54),
            new KeyValuePair<int,int>(32,42),
            new KeyValuePair<int,int>(33,56),
            new KeyValuePair<int,int>(34,29),
            new KeyValuePair<int,int>(35,34),
            new KeyValuePair<int,int>(36,13),
        };

        public List<KeyValuePair<int, int>> Deuteronomy = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,46),
            new KeyValuePair<int,int>(2,37),
            new KeyValuePair<int,int>(3,29),
            new KeyValuePair<int,int>(4,49),
            new KeyValuePair<int,int>(5,33),
            new KeyValuePair<int,int>(6,25),
            new KeyValuePair<int,int>(7,26),
            new KeyValuePair<int,int>(8,20),
            new KeyValuePair<int,int>(9,29),
            new KeyValuePair<int,int>(10,22),
            new KeyValuePair<int,int>(11,32),
            new KeyValuePair<int,int>(12,32),
            new KeyValuePair<int,int>(13,18),
            new KeyValuePair<int,int>(14,29),
            new KeyValuePair<int,int>(15,23),
            new KeyValuePair<int,int>(16,22),
            new KeyValuePair<int,int>(17,20),
            new KeyValuePair<int,int>(18,22),
            new KeyValuePair<int,int>(19,21),
            new KeyValuePair<int,int>(20,20),
            new KeyValuePair<int,int>(21,23),
            new KeyValuePair<int,int>(22,30),
            new KeyValuePair<int,int>(23,25),
            new KeyValuePair<int,int>(24,22),
            new KeyValuePair<int,int>(25,19),
            new KeyValuePair<int,int>(26,19),
            new KeyValuePair<int,int>(27,26),
            new KeyValuePair<int,int>(28,68),
            new KeyValuePair<int,int>(29,29),
            new KeyValuePair<int,int>(30,20),
            new KeyValuePair<int,int>(31,30),
            new KeyValuePair<int,int>(32,52),
            new KeyValuePair<int,int>(33,29),
            new KeyValuePair<int,int>(34,12),
        };

        public List<KeyValuePair<int, int>> Joshua = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,18),
            new KeyValuePair<int,int>(2,24),
            new KeyValuePair<int,int>(3,17),
            new KeyValuePair<int,int>(4,24),
            new KeyValuePair<int,int>(5,15),
            new KeyValuePair<int,int>(6,27),
            new KeyValuePair<int,int>(7,26),
            new KeyValuePair<int,int>(8,35),
            new KeyValuePair<int,int>(9,27),
            new KeyValuePair<int,int>(10,43),
            new KeyValuePair<int,int>(11,23),
            new KeyValuePair<int,int>(12,24),
            new KeyValuePair<int,int>(13,33),
            new KeyValuePair<int,int>(14,15),
            new KeyValuePair<int,int>(15,63),
            new KeyValuePair<int,int>(16,10),
            new KeyValuePair<int,int>(17,18),
            new KeyValuePair<int,int>(18,28),
            new KeyValuePair<int,int>(19,51),
            new KeyValuePair<int,int>(20,9),
            new KeyValuePair<int,int>(21,45),
            new KeyValuePair<int,int>(22,34),
            new KeyValuePair<int,int>(23,16),
            new KeyValuePair<int,int>(24,33),
        };

        public List<KeyValuePair<int, int>> Judges = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,36),
            new KeyValuePair<int,int>(2,23),
            new KeyValuePair<int,int>(3,31),
            new KeyValuePair<int,int>(4,24),
            new KeyValuePair<int,int>(5,31),
            new KeyValuePair<int,int>(6,40),
            new KeyValuePair<int,int>(7,25),
            new KeyValuePair<int,int>(8,35),
            new KeyValuePair<int,int>(9,57),
            new KeyValuePair<int,int>(10,18),
            new KeyValuePair<int,int>(11,40),
            new KeyValuePair<int,int>(12,15),
            new KeyValuePair<int,int>(13,25),
            new KeyValuePair<int,int>(14,20),
            new KeyValuePair<int,int>(15,20),
            new KeyValuePair<int,int>(16,31),
            new KeyValuePair<int,int>(17,13),
            new KeyValuePair<int,int>(18,31),
            new KeyValuePair<int,int>(19,30),
            new KeyValuePair<int,int>(20,48),
            new KeyValuePair<int,int>(21,25),
        };

        public List<KeyValuePair<int, int>> Ruth = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,22),
            new KeyValuePair<int,int>(2,23),
            new KeyValuePair<int,int>(3,18),
            new KeyValuePair<int,int>(4,22),
        };

        public List<KeyValuePair<int, int>> First_Samuel = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,28),
            new KeyValuePair<int,int>(2,36),
            new KeyValuePair<int,int>(3,21),
            new KeyValuePair<int,int>(4,22),
            new KeyValuePair<int,int>(5,12),
            new KeyValuePair<int,int>(6,21),
            new KeyValuePair<int,int>(7,17),
            new KeyValuePair<int,int>(8,22),
            new KeyValuePair<int,int>(9,27),
            new KeyValuePair<int,int>(10,27),
            new KeyValuePair<int,int>(11,15),
            new KeyValuePair<int,int>(12,25),
            new KeyValuePair<int,int>(13,23),
            new KeyValuePair<int,int>(14,52),
            new KeyValuePair<int,int>(15,35),
            new KeyValuePair<int,int>(16,23),
            new KeyValuePair<int,int>(17,58),
            new KeyValuePair<int,int>(18,30),
            new KeyValuePair<int,int>(19,24),
            new KeyValuePair<int,int>(20,42),
            new KeyValuePair<int,int>(21,15),
            new KeyValuePair<int,int>(22,23),
            new KeyValuePair<int,int>(23,29),
            new KeyValuePair<int,int>(24,22),
            new KeyValuePair<int,int>(25,44),
            new KeyValuePair<int,int>(26,25),
            new KeyValuePair<int,int>(27,12),
            new KeyValuePair<int,int>(28,25),
            new KeyValuePair<int,int>(29,11),
            new KeyValuePair<int,int>(30,31),
            new KeyValuePair<int,int>(31,13),
        };

        public List<KeyValuePair<int, int>> Second_Samuel = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,27),
            new KeyValuePair<int,int>(2,32),
            new KeyValuePair<int,int>(3,39),
            new KeyValuePair<int,int>(4,12),
            new KeyValuePair<int,int>(5,25),
            new KeyValuePair<int,int>(6,23),
            new KeyValuePair<int,int>(7,29),
            new KeyValuePair<int,int>(8,18),
            new KeyValuePair<int,int>(9,13),
            new KeyValuePair<int,int>(10,19),
            new KeyValuePair<int,int>(11,27),
            new KeyValuePair<int,int>(12,31),
            new KeyValuePair<int,int>(13,39),
            new KeyValuePair<int,int>(14,33),
            new KeyValuePair<int,int>(15,37),
            new KeyValuePair<int,int>(16,23),
            new KeyValuePair<int,int>(17,29),
            new KeyValuePair<int,int>(18,33),
            new KeyValuePair<int,int>(19,43),
            new KeyValuePair<int,int>(20,26),
            new KeyValuePair<int,int>(21,22),
            new KeyValuePair<int,int>(22,51),
            new KeyValuePair<int,int>(23,39),
            new KeyValuePair<int,int>(24,25),
        };

        public List<KeyValuePair<int, int>> First_Kings = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,53),
            new KeyValuePair<int,int>(2,46),
            new KeyValuePair<int,int>(3,28),
            new KeyValuePair<int,int>(4,34),
            new KeyValuePair<int,int>(5,18),
            new KeyValuePair<int,int>(6,38),
            new KeyValuePair<int,int>(7,51),
            new KeyValuePair<int,int>(8,66),
            new KeyValuePair<int,int>(9,28),
            new KeyValuePair<int,int>(10,29),
            new KeyValuePair<int,int>(11,43),
            new KeyValuePair<int,int>(12,33),
            new KeyValuePair<int,int>(13,34),
            new KeyValuePair<int,int>(14,31),
            new KeyValuePair<int,int>(15,34),
            new KeyValuePair<int,int>(16,34),
            new KeyValuePair<int,int>(17,24),
            new KeyValuePair<int,int>(18,46),
            new KeyValuePair<int,int>(19,21),
            new KeyValuePair<int,int>(20,43),
            new KeyValuePair<int,int>(21,29),
            new KeyValuePair<int,int>(22,53),
        };

        public List<KeyValuePair<int, int>> Second_Kings = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,18),
            new KeyValuePair<int,int>(2,25),
            new KeyValuePair<int,int>(3,27),
            new KeyValuePair<int,int>(4,44),
            new KeyValuePair<int,int>(5,27),
            new KeyValuePair<int,int>(6,33),
            new KeyValuePair<int,int>(7,20),
            new KeyValuePair<int,int>(8,29),
            new KeyValuePair<int,int>(9,37),
            new KeyValuePair<int,int>(10,36),
            new KeyValuePair<int,int>(11,21),
            new KeyValuePair<int,int>(12,21),
            new KeyValuePair<int,int>(13,25),
            new KeyValuePair<int,int>(14,29),
            new KeyValuePair<int,int>(15,38),
            new KeyValuePair<int,int>(16,20),
            new KeyValuePair<int,int>(17,41),
            new KeyValuePair<int,int>(18,37),
            new KeyValuePair<int,int>(19,37),
            new KeyValuePair<int,int>(20,21),
            new KeyValuePair<int,int>(21,26),
            new KeyValuePair<int,int>(22,20),
            new KeyValuePair<int,int>(23,37),
            new KeyValuePair<int,int>(24,20),
            new KeyValuePair<int,int>(25,30),
        };

        public List<KeyValuePair<int, int>> First_Chronicles = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,54),
            new KeyValuePair<int,int>(2,55),
            new KeyValuePair<int,int>(3,24),
            new KeyValuePair<int,int>(4,43),
            new KeyValuePair<int,int>(5,26),
            new KeyValuePair<int,int>(6,81),
            new KeyValuePair<int,int>(7,40),
            new KeyValuePair<int,int>(8,40),
            new KeyValuePair<int,int>(9,44),
            new KeyValuePair<int,int>(10,14),
            new KeyValuePair<int,int>(11,47),
            new KeyValuePair<int,int>(12,40),
            new KeyValuePair<int,int>(13,14),
            new KeyValuePair<int,int>(14,17),
            new KeyValuePair<int,int>(15,29),
            new KeyValuePair<int,int>(16,43),
            new KeyValuePair<int,int>(17,27),
            new KeyValuePair<int,int>(18,18),
            new KeyValuePair<int,int>(19,18),
            new KeyValuePair<int,int>(20,8),
            new KeyValuePair<int,int>(21,30),
            new KeyValuePair<int,int>(22,19),
            new KeyValuePair<int,int>(23,32),
            new KeyValuePair<int,int>(24,31),
            new KeyValuePair<int,int>(25,31),
            new KeyValuePair<int,int>(26,32),
            new KeyValuePair<int,int>(27,34),
            new KeyValuePair<int,int>(28,21),
            new KeyValuePair<int,int>(29,30),
        };

        public List<KeyValuePair<int, int>> Second_Chronicles = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,17),
            new KeyValuePair<int,int>(2,18),
            new KeyValuePair<int,int>(3,17),
            new KeyValuePair<int,int>(4,22),
            new KeyValuePair<int,int>(5,14),
            new KeyValuePair<int,int>(6,42),
            new KeyValuePair<int,int>(7,22),
            new KeyValuePair<int,int>(8,18),
            new KeyValuePair<int,int>(9,31),
            new KeyValuePair<int,int>(10,19),
            new KeyValuePair<int,int>(11,23),
            new KeyValuePair<int,int>(12,16),
            new KeyValuePair<int,int>(13,22),
            new KeyValuePair<int,int>(14,15),
            new KeyValuePair<int,int>(15,19),
            new KeyValuePair<int,int>(16,14),
            new KeyValuePair<int,int>(17,19),
            new KeyValuePair<int,int>(18,34),
            new KeyValuePair<int,int>(19,11),
            new KeyValuePair<int,int>(20,37),
            new KeyValuePair<int,int>(21,20),
            new KeyValuePair<int,int>(22,12),
            new KeyValuePair<int,int>(23,21),
            new KeyValuePair<int,int>(24,27),
            new KeyValuePair<int,int>(25,28),
            new KeyValuePair<int,int>(26,23),
            new KeyValuePair<int,int>(27,9),
            new KeyValuePair<int,int>(28,27),
            new KeyValuePair<int,int>(29,36),
            new KeyValuePair<int,int>(30,27),
            new KeyValuePair<int,int>(31,21),
            new KeyValuePair<int,int>(32,33),
            new KeyValuePair<int,int>(33,25),
            new KeyValuePair<int,int>(34,33),
            new KeyValuePair<int,int>(35,27),
            new KeyValuePair<int,int>(36,23),
        };

        public List<KeyValuePair<int, int>> Ezra = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,11),
            new KeyValuePair<int,int>(2,70),
            new KeyValuePair<int,int>(3,13),
            new KeyValuePair<int,int>(4,24),
            new KeyValuePair<int,int>(5,17),
            new KeyValuePair<int,int>(6,22),
            new KeyValuePair<int,int>(7,28),
            new KeyValuePair<int,int>(8,36),
            new KeyValuePair<int,int>(9,15),
            new KeyValuePair<int,int>(10,44),
        };

        public List<KeyValuePair<int, int>> Nehemiah = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,11),
            new KeyValuePair<int,int>(2,20),
            new KeyValuePair<int,int>(3,32),
            new KeyValuePair<int,int>(4,23),
            new KeyValuePair<int,int>(5,19),
            new KeyValuePair<int,int>(6,19),
            new KeyValuePair<int,int>(7,73),
            new KeyValuePair<int,int>(8,18),
            new KeyValuePair<int,int>(9,38),
            new KeyValuePair<int,int>(10,39),
            new KeyValuePair<int,int>(11,36),
            new KeyValuePair<int,int>(12,47),
            new KeyValuePair<int,int>(13,31),
        };

        public List<KeyValuePair<int, int>> Esther = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,22),
            new KeyValuePair<int,int>(2,23),
            new KeyValuePair<int,int>(3,15),
            new KeyValuePair<int,int>(4,17),
            new KeyValuePair<int,int>(5,14),
            new KeyValuePair<int,int>(6,14),
            new KeyValuePair<int,int>(7,10),
            new KeyValuePair<int,int>(8,17),
            new KeyValuePair<int,int>(9,32),
            new KeyValuePair<int,int>(10,3),
        };

        public List<KeyValuePair<int, int>> Job = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,22),
            new KeyValuePair<int,int>(2,13),
            new KeyValuePair<int,int>(3,26),
            new KeyValuePair<int,int>(4,21),
            new KeyValuePair<int,int>(5,27),
            new KeyValuePair<int,int>(6,30),
            new KeyValuePair<int,int>(7,21),
            new KeyValuePair<int,int>(8,22),
            new KeyValuePair<int,int>(9,35),
            new KeyValuePair<int,int>(10,22),
            new KeyValuePair<int,int>(11,20),
            new KeyValuePair<int,int>(12,25),
            new KeyValuePair<int,int>(13,28),
            new KeyValuePair<int,int>(14,22),
            new KeyValuePair<int,int>(15,35),
            new KeyValuePair<int,int>(16,22),
            new KeyValuePair<int,int>(17,16),
            new KeyValuePair<int,int>(18,21),
            new KeyValuePair<int,int>(19,29),
            new KeyValuePair<int,int>(20,29),
            new KeyValuePair<int,int>(21,34),
            new KeyValuePair<int,int>(22,30),
            new KeyValuePair<int,int>(23,17),
            new KeyValuePair<int,int>(24,25),
            new KeyValuePair<int,int>(25,6),
            new KeyValuePair<int,int>(26,14),
            new KeyValuePair<int,int>(27,23),
            new KeyValuePair<int,int>(28,28),
            new KeyValuePair<int,int>(29,25),
            new KeyValuePair<int,int>(30,31),
            new KeyValuePair<int,int>(31,40),
            new KeyValuePair<int,int>(32,22),
            new KeyValuePair<int,int>(33,33),
            new KeyValuePair<int,int>(34,37),
            new KeyValuePair<int,int>(35,16),
            new KeyValuePair<int,int>(36,33),
            new KeyValuePair<int,int>(37,24),
            new KeyValuePair<int,int>(38,41),
            new KeyValuePair<int,int>(39,30),
            new KeyValuePair<int,int>(40,24),
            new KeyValuePair<int,int>(41,34),
            new KeyValuePair<int,int>(42,17),
        };

        public List<KeyValuePair<int, int>> Psalms = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,6),
            new KeyValuePair<int,int>(2,12),
            new KeyValuePair<int,int>(3,8),
            new KeyValuePair<int,int>(4,8),
            new KeyValuePair<int,int>(5,12),
            new KeyValuePair<int,int>(6,10),
            new KeyValuePair<int,int>(7,17),
            new KeyValuePair<int,int>(8,9),
            new KeyValuePair<int,int>(9,20),
            new KeyValuePair<int,int>(10,18),
            new KeyValuePair<int,int>(11,7),
            new KeyValuePair<int,int>(12,8),
            new KeyValuePair<int,int>(13,6),
            new KeyValuePair<int,int>(14,7),
            new KeyValuePair<int,int>(15,5),
            new KeyValuePair<int,int>(16,11),
            new KeyValuePair<int,int>(17,15),
            new KeyValuePair<int,int>(18,50),
            new KeyValuePair<int,int>(19,14),
            new KeyValuePair<int,int>(20,9),
            new KeyValuePair<int,int>(21,13),
            new KeyValuePair<int,int>(22,31),
            new KeyValuePair<int,int>(23,6),
            new KeyValuePair<int,int>(24,10),
            new KeyValuePair<int,int>(25,22),
            new KeyValuePair<int,int>(26,12),
            new KeyValuePair<int,int>(27,14),
            new KeyValuePair<int,int>(28,9),
            new KeyValuePair<int,int>(29,11),
            new KeyValuePair<int,int>(30,12),
            new KeyValuePair<int,int>(31,24),
            new KeyValuePair<int,int>(32,11),
            new KeyValuePair<int,int>(33,22),
            new KeyValuePair<int,int>(34,22),
            new KeyValuePair<int,int>(35,28),
            new KeyValuePair<int,int>(36,12),
            new KeyValuePair<int,int>(37,40),
            new KeyValuePair<int,int>(38,22),
            new KeyValuePair<int,int>(39,13),
            new KeyValuePair<int,int>(40,17),
            new KeyValuePair<int,int>(41,13),
            new KeyValuePair<int,int>(42,11),
            new KeyValuePair<int,int>(43,5),
            new KeyValuePair<int,int>(44,26),
            new KeyValuePair<int,int>(45,17),
            new KeyValuePair<int,int>(46,11),
            new KeyValuePair<int,int>(47,9),
            new KeyValuePair<int,int>(48,14),
            new KeyValuePair<int,int>(49,20),
            new KeyValuePair<int,int>(50,23),
            new KeyValuePair<int,int>(51,19),
            new KeyValuePair<int,int>(52,9),
            new KeyValuePair<int,int>(53,6),
            new KeyValuePair<int,int>(54,7),
            new KeyValuePair<int,int>(55,23),
            new KeyValuePair<int,int>(56,13),
            new KeyValuePair<int,int>(57,11),
            new KeyValuePair<int,int>(58,11),
            new KeyValuePair<int,int>(59,17),
            new KeyValuePair<int,int>(60,12),
            new KeyValuePair<int,int>(61,8),
            new KeyValuePair<int,int>(62,12),
            new KeyValuePair<int,int>(63,11),
            new KeyValuePair<int,int>(64,10),
            new KeyValuePair<int,int>(65,13),
            new KeyValuePair<int,int>(66,20),
            new KeyValuePair<int,int>(67,7),
            new KeyValuePair<int,int>(68,35),
            new KeyValuePair<int,int>(69,36),
            new KeyValuePair<int,int>(70,5),
            new KeyValuePair<int,int>(71,24),
            new KeyValuePair<int,int>(72,20),
            new KeyValuePair<int,int>(73,28),
            new KeyValuePair<int,int>(74,23),
            new KeyValuePair<int,int>(75,10),
            new KeyValuePair<int,int>(76,12),
            new KeyValuePair<int,int>(77,20),
            new KeyValuePair<int,int>(78,72),
            new KeyValuePair<int,int>(79,13),
            new KeyValuePair<int,int>(80,19),
            new KeyValuePair<int,int>(81,16),
            new KeyValuePair<int,int>(82,8),
            new KeyValuePair<int,int>(83,18),
            new KeyValuePair<int,int>(84,12),
            new KeyValuePair<int,int>(85,13),
            new KeyValuePair<int,int>(86,17),
            new KeyValuePair<int,int>(87,7),
            new KeyValuePair<int,int>(88,18),
            new KeyValuePair<int,int>(89,52),
            new KeyValuePair<int,int>(90,17),
            new KeyValuePair<int,int>(91,16),
            new KeyValuePair<int,int>(92,15),
            new KeyValuePair<int,int>(93,5),
            new KeyValuePair<int,int>(94,23),
            new KeyValuePair<int,int>(95,11),
            new KeyValuePair<int,int>(96,13),
            new KeyValuePair<int,int>(97,12),
            new KeyValuePair<int,int>(98,9),
            new KeyValuePair<int,int>(99,9),
            new KeyValuePair<int,int>(100,5),
            new KeyValuePair<int,int>(101,8),
            new KeyValuePair<int,int>(102,28),
            new KeyValuePair<int,int>(103,22),
            new KeyValuePair<int,int>(104,35),
            new KeyValuePair<int,int>(105,45),
            new KeyValuePair<int,int>(106,48),
            new KeyValuePair<int,int>(107,43),
            new KeyValuePair<int,int>(108,13),
            new KeyValuePair<int,int>(109,31),
            new KeyValuePair<int,int>(110,7),
            new KeyValuePair<int,int>(111,10),
            new KeyValuePair<int,int>(112,10),
            new KeyValuePair<int,int>(113,9),
            new KeyValuePair<int,int>(114,8),
            new KeyValuePair<int,int>(115,18),
            new KeyValuePair<int,int>(116,19),
            new KeyValuePair<int,int>(117,2),
            new KeyValuePair<int,int>(118,29),
            new KeyValuePair<int,int>(119,176),
            new KeyValuePair<int,int>(120,7),
            new KeyValuePair<int,int>(121,8),
            new KeyValuePair<int,int>(122,9),
            new KeyValuePair<int,int>(123,4),
            new KeyValuePair<int,int>(124,8),
            new KeyValuePair<int,int>(125,5),
            new KeyValuePair<int,int>(126,6),
            new KeyValuePair<int,int>(127,5),
            new KeyValuePair<int,int>(128,6),
            new KeyValuePair<int,int>(129,8),
            new KeyValuePair<int,int>(130,8),
            new KeyValuePair<int,int>(131,3),
            new KeyValuePair<int,int>(132,18),
            new KeyValuePair<int,int>(133,3),
            new KeyValuePair<int,int>(134,3),
            new KeyValuePair<int,int>(135,21),
            new KeyValuePair<int,int>(136,26),
            new KeyValuePair<int,int>(137,9),
            new KeyValuePair<int,int>(138,8),
            new KeyValuePair<int,int>(139,24),
            new KeyValuePair<int,int>(140,13),
            new KeyValuePair<int,int>(141,10),
            new KeyValuePair<int,int>(142,7),
            new KeyValuePair<int,int>(143,12),
            new KeyValuePair<int,int>(144,15),
            new KeyValuePair<int,int>(145,21),
            new KeyValuePair<int,int>(146,10),
            new KeyValuePair<int,int>(147,20),
            new KeyValuePair<int,int>(148,14),
            new KeyValuePair<int,int>(149,9),
            new KeyValuePair<int,int>(150,6),
        };

        public List<KeyValuePair<int, int>> Proverbs = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,33),
            new KeyValuePair<int,int>(2,22),
            new KeyValuePair<int,int>(3,35),
            new KeyValuePair<int,int>(4,27),
            new KeyValuePair<int,int>(5,23),
            new KeyValuePair<int,int>(6,35),
            new KeyValuePair<int,int>(7,27),
            new KeyValuePair<int,int>(8,36),
            new KeyValuePair<int,int>(9,18),
            new KeyValuePair<int,int>(10,32),
            new KeyValuePair<int,int>(11,31),
            new KeyValuePair<int,int>(12,28),
            new KeyValuePair<int,int>(13,25),
            new KeyValuePair<int,int>(14,35),
            new KeyValuePair<int,int>(15,33),
            new KeyValuePair<int,int>(16,33),
            new KeyValuePair<int,int>(17,28),
            new KeyValuePair<int,int>(18,24),
            new KeyValuePair<int,int>(19,29),
            new KeyValuePair<int,int>(20,30),
            new KeyValuePair<int,int>(21,31),
            new KeyValuePair<int,int>(22,29),
            new KeyValuePair<int,int>(23,35),
            new KeyValuePair<int,int>(24,34),
            new KeyValuePair<int,int>(25,28),
            new KeyValuePair<int,int>(26,28),
            new KeyValuePair<int,int>(27,27),
            new KeyValuePair<int,int>(28,28),
            new KeyValuePair<int,int>(29,27),
            new KeyValuePair<int,int>(30,33),
            new KeyValuePair<int,int>(31,31),
        };

        public List<KeyValuePair<int, int>> Ecclesiastes = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,18),
            new KeyValuePair<int,int>(2,26),
            new KeyValuePair<int,int>(3,22),
            new KeyValuePair<int,int>(4,16),
            new KeyValuePair<int,int>(5,20),
            new KeyValuePair<int,int>(6,12),
            new KeyValuePair<int,int>(7,29),
            new KeyValuePair<int,int>(8,17),
            new KeyValuePair<int,int>(9,18),
            new KeyValuePair<int,int>(10,20),
            new KeyValuePair<int,int>(11,10),
            new KeyValuePair<int,int>(12,14),
        };

        public List<KeyValuePair<int, int>> Song_of_Solomon = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,17),
            new KeyValuePair<int,int>(2,17),
            new KeyValuePair<int,int>(3,11),
            new KeyValuePair<int,int>(4,16),
            new KeyValuePair<int,int>(5,16),
            new KeyValuePair<int,int>(6,13),
            new KeyValuePair<int,int>(7,13),
            new KeyValuePair<int,int>(8,14),
        };

        public List<KeyValuePair<int, int>> Isaiah = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,31),
            new KeyValuePair<int,int>(2,22),
            new KeyValuePair<int,int>(3,26),
            new KeyValuePair<int,int>(4,6),
            new KeyValuePair<int,int>(5,30),
            new KeyValuePair<int,int>(6,13),
            new KeyValuePair<int,int>(7,25),
            new KeyValuePair<int,int>(8,22),
            new KeyValuePair<int,int>(9,21),
            new KeyValuePair<int,int>(10,34),
            new KeyValuePair<int,int>(11,16),
            new KeyValuePair<int,int>(12,6),
            new KeyValuePair<int,int>(13,22),
            new KeyValuePair<int,int>(14,32),
            new KeyValuePair<int,int>(15,9),
            new KeyValuePair<int,int>(16,14),
            new KeyValuePair<int,int>(17,14),
            new KeyValuePair<int,int>(18,7),
            new KeyValuePair<int,int>(19,25),
            new KeyValuePair<int,int>(20,6),
            new KeyValuePair<int,int>(21,17),
            new KeyValuePair<int,int>(22,25),
            new KeyValuePair<int,int>(23,18),
            new KeyValuePair<int,int>(24,23),
            new KeyValuePair<int,int>(25,12),
            new KeyValuePair<int,int>(26,21),
            new KeyValuePair<int,int>(27,13),
            new KeyValuePair<int,int>(28,29),
            new KeyValuePair<int,int>(29,24),
            new KeyValuePair<int,int>(30,33),
            new KeyValuePair<int,int>(31,9),
            new KeyValuePair<int,int>(32,20),
            new KeyValuePair<int,int>(33,24),
            new KeyValuePair<int,int>(34,17),
            new KeyValuePair<int,int>(35,10),
            new KeyValuePair<int,int>(36,22),
            new KeyValuePair<int,int>(37,38),
            new KeyValuePair<int,int>(38,22),
            new KeyValuePair<int,int>(39,8),
            new KeyValuePair<int,int>(40,31),
            new KeyValuePair<int,int>(41,29),
            new KeyValuePair<int,int>(42,25),
            new KeyValuePair<int,int>(43,28),
            new KeyValuePair<int,int>(44,28),
            new KeyValuePair<int,int>(45,25),
            new KeyValuePair<int,int>(46,13),
            new KeyValuePair<int,int>(47,15),
            new KeyValuePair<int,int>(48,22),
            new KeyValuePair<int,int>(49,26),
            new KeyValuePair<int,int>(50,11),
            new KeyValuePair<int,int>(51,23),
            new KeyValuePair<int,int>(52,15),
            new KeyValuePair<int,int>(53,12),
            new KeyValuePair<int,int>(54,17),
            new KeyValuePair<int,int>(55,13),
            new KeyValuePair<int,int>(56,12),
            new KeyValuePair<int,int>(57,21),
            new KeyValuePair<int,int>(58,14),
            new KeyValuePair<int,int>(59,21),
            new KeyValuePair<int,int>(60,22),
            new KeyValuePair<int,int>(61,11),
            new KeyValuePair<int,int>(62,12),
            new KeyValuePair<int,int>(63,19),
            new KeyValuePair<int,int>(64,12),
            new KeyValuePair<int,int>(65,25),
            new KeyValuePair<int,int>(66,24),
        };

        public List<KeyValuePair<int, int>> Jeremiah = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,19),
            new KeyValuePair<int,int>(2,37),
            new KeyValuePair<int,int>(3,25),
            new KeyValuePair<int,int>(4,31),
            new KeyValuePair<int,int>(5,31),
            new KeyValuePair<int,int>(6,30),
            new KeyValuePair<int,int>(7,34),
            new KeyValuePair<int,int>(8,22),
            new KeyValuePair<int,int>(9,26),
            new KeyValuePair<int,int>(10,25),
            new KeyValuePair<int,int>(11,23),
            new KeyValuePair<int,int>(12,17),
            new KeyValuePair<int,int>(13,27),
            new KeyValuePair<int,int>(14,22),
            new KeyValuePair<int,int>(15,21),
            new KeyValuePair<int,int>(16,21),
            new KeyValuePair<int,int>(17,27),
            new KeyValuePair<int,int>(18,23),
            new KeyValuePair<int,int>(19,15),
            new KeyValuePair<int,int>(20,18),
            new KeyValuePair<int,int>(21,14),
            new KeyValuePair<int,int>(22,30),
            new KeyValuePair<int,int>(23,40),
            new KeyValuePair<int,int>(24,10),
            new KeyValuePair<int,int>(25,38),
            new KeyValuePair<int,int>(26,24),
            new KeyValuePair<int,int>(27,22),
            new KeyValuePair<int,int>(28,17),
            new KeyValuePair<int,int>(29,32),
            new KeyValuePair<int,int>(30,24),
            new KeyValuePair<int,int>(31,40),
            new KeyValuePair<int,int>(32,44),
            new KeyValuePair<int,int>(33,26),
            new KeyValuePair<int,int>(34,22),
            new KeyValuePair<int,int>(35,19),
            new KeyValuePair<int,int>(36,32),
            new KeyValuePair<int,int>(37,21),
            new KeyValuePair<int,int>(38,28),
            new KeyValuePair<int,int>(39,18),
            new KeyValuePair<int,int>(40,16),
            new KeyValuePair<int,int>(41,18),
            new KeyValuePair<int,int>(42,22),
            new KeyValuePair<int,int>(43,13),
            new KeyValuePair<int,int>(44,30),
            new KeyValuePair<int,int>(45,5),
            new KeyValuePair<int,int>(46,28),
            new KeyValuePair<int,int>(47,7),
            new KeyValuePair<int,int>(48,47),
            new KeyValuePair<int,int>(49,39),
            new KeyValuePair<int,int>(50,46),
            new KeyValuePair<int,int>(51,64),
            new KeyValuePair<int,int>(52,34),
        };

        public List<KeyValuePair<int, int>> Ezekiel = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,28),
            new KeyValuePair<int,int>(2,10),
            new KeyValuePair<int,int>(3,27),
            new KeyValuePair<int,int>(4,17),
            new KeyValuePair<int,int>(5,17),
            new KeyValuePair<int,int>(6,14),
            new KeyValuePair<int,int>(7,27),
            new KeyValuePair<int,int>(8,18),
            new KeyValuePair<int,int>(9,11),
            new KeyValuePair<int,int>(10,22),
            new KeyValuePair<int,int>(11,25),
            new KeyValuePair<int,int>(12,28),
            new KeyValuePair<int,int>(13,23),
            new KeyValuePair<int,int>(14,23),
            new KeyValuePair<int,int>(15,8),
            new KeyValuePair<int,int>(16,63),
            new KeyValuePair<int,int>(17,24),
            new KeyValuePair<int,int>(18,32),
            new KeyValuePair<int,int>(19,14),
            new KeyValuePair<int,int>(20,49),
            new KeyValuePair<int,int>(21,32),
            new KeyValuePair<int,int>(22,31),
            new KeyValuePair<int,int>(23,49),
            new KeyValuePair<int,int>(24,27),
            new KeyValuePair<int,int>(25,17),
            new KeyValuePair<int,int>(26,21),
            new KeyValuePair<int,int>(27,36),
            new KeyValuePair<int,int>(28,26),
            new KeyValuePair<int,int>(29,21),
            new KeyValuePair<int,int>(30,26),
            new KeyValuePair<int,int>(31,18),
            new KeyValuePair<int,int>(32,32),
            new KeyValuePair<int,int>(33,33),
            new KeyValuePair<int,int>(34,31),
            new KeyValuePair<int,int>(35,15),
            new KeyValuePair<int,int>(36,38),
            new KeyValuePair<int,int>(37,28),
            new KeyValuePair<int,int>(38,23),
            new KeyValuePair<int,int>(39,29),
            new KeyValuePair<int,int>(40,49),
            new KeyValuePair<int,int>(41,26),
            new KeyValuePair<int,int>(42,20),
            new KeyValuePair<int,int>(43,27),
            new KeyValuePair<int,int>(44,31),
            new KeyValuePair<int,int>(45,25),
            new KeyValuePair<int,int>(46,24),
            new KeyValuePair<int,int>(47,23),
            new KeyValuePair<int,int>(48,35),
        };

        public List<KeyValuePair<int, int>> Daniel = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,21),
            new KeyValuePair<int,int>(2,49),
            new KeyValuePair<int,int>(3,30),
            new KeyValuePair<int,int>(4,37),
            new KeyValuePair<int,int>(5,31),
            new KeyValuePair<int,int>(6,28),
            new KeyValuePair<int,int>(7,28),
            new KeyValuePair<int,int>(8,27),
            new KeyValuePair<int,int>(9,27),
            new KeyValuePair<int,int>(10,21),
            new KeyValuePair<int,int>(11,45),
            new KeyValuePair<int,int>(12,13),
        };

        public List<KeyValuePair<int, int>> Hosea = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,11),
            new KeyValuePair<int,int>(2,23),
            new KeyValuePair<int,int>(3,5),
            new KeyValuePair<int,int>(4,19),
            new KeyValuePair<int,int>(5,15),
            new KeyValuePair<int,int>(6,11),
            new KeyValuePair<int,int>(7,16),
            new KeyValuePair<int,int>(8,14),
            new KeyValuePair<int,int>(9,17),
            new KeyValuePair<int,int>(10,15),
            new KeyValuePair<int,int>(11,12),
            new KeyValuePair<int,int>(12,14),
            new KeyValuePair<int,int>(13,16),
            new KeyValuePair<int,int>(14,9),
        };

        public List<KeyValuePair<int, int>> Joel = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,20),
            new KeyValuePair<int,int>(2,32),
            new KeyValuePair<int,int>(3,21),
        };

        public List<KeyValuePair<int, int>> Amos = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,15),
            new KeyValuePair<int,int>(2,16),
            new KeyValuePair<int,int>(3,15),
            new KeyValuePair<int,int>(4,13),
            new KeyValuePair<int,int>(5,27),
            new KeyValuePair<int,int>(6,14),
            new KeyValuePair<int,int>(7,17),
            new KeyValuePair<int,int>(8,14),
            new KeyValuePair<int,int>(9,15),
        };

        public List<KeyValuePair<int, int>> Obadiah = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,21),
        };

        public List<KeyValuePair<int, int>> Jonah = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,17),
            new KeyValuePair<int,int>(2,10),
            new KeyValuePair<int,int>(3,10),
            new KeyValuePair<int,int>(4,11),
        };

        public List<KeyValuePair<int, int>> Micah = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,16),
            new KeyValuePair<int,int>(2,13),
            new KeyValuePair<int,int>(3,12),
            new KeyValuePair<int,int>(4,13),
            new KeyValuePair<int,int>(5,15),
            new KeyValuePair<int,int>(6,16),
            new KeyValuePair<int,int>(7,20),
        };

        public List<KeyValuePair<int, int>> Nahum = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,15),
            new KeyValuePair<int,int>(2,13),
            new KeyValuePair<int,int>(3,19),
        };

        public List<KeyValuePair<int, int>> Habakkuk = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,17),
            new KeyValuePair<int,int>(2,20),
            new KeyValuePair<int,int>(3,19),
        };

        public List<KeyValuePair<int, int>> Zephaniah = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,18),
            new KeyValuePair<int,int>(2,15),
            new KeyValuePair<int,int>(3,20),
        };

        public List<KeyValuePair<int, int>> Haggai = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,15),
            new KeyValuePair<int,int>(2,23),
        };

        public List<KeyValuePair<int, int>> Zechariah = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,21),
            new KeyValuePair<int,int>(2,13),
            new KeyValuePair<int,int>(3,10),
            new KeyValuePair<int,int>(4,14),
            new KeyValuePair<int,int>(5,11),
            new KeyValuePair<int,int>(6,15),
            new KeyValuePair<int,int>(7,14),
            new KeyValuePair<int,int>(8,23),
            new KeyValuePair<int,int>(9,17),
            new KeyValuePair<int,int>(10,12),
            new KeyValuePair<int,int>(11,17),
            new KeyValuePair<int,int>(12,14),
            new KeyValuePair<int,int>(13,9),
            new KeyValuePair<int,int>(14,21),
        };

        public List<KeyValuePair<int, int>> Malachi = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,14),
            new KeyValuePair<int,int>(2,17),
            new KeyValuePair<int,int>(3,18),
            new KeyValuePair<int,int>(4,6),
        };

        public List<KeyValuePair<int, int>> Matthew = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,25),
            new KeyValuePair<int,int>(2,23),
            new KeyValuePair<int,int>(3,17),
            new KeyValuePair<int,int>(4,25),
            new KeyValuePair<int,int>(5,48),
            new KeyValuePair<int,int>(6,34),
            new KeyValuePair<int,int>(7,29),
            new KeyValuePair<int,int>(8,34),
            new KeyValuePair<int,int>(9,38),
            new KeyValuePair<int,int>(10,42),
            new KeyValuePair<int,int>(11,30),
            new KeyValuePair<int,int>(12,50),
            new KeyValuePair<int,int>(13,58),
            new KeyValuePair<int,int>(14,36),
            new KeyValuePair<int,int>(15,39),
            new KeyValuePair<int,int>(16,28),
            new KeyValuePair<int,int>(17,27),
            new KeyValuePair<int,int>(18,35),
            new KeyValuePair<int,int>(19,30),
            new KeyValuePair<int,int>(20,34),
            new KeyValuePair<int,int>(21,46),
            new KeyValuePair<int,int>(22,46),
            new KeyValuePair<int,int>(23,39),
            new KeyValuePair<int,int>(24,51),
            new KeyValuePair<int,int>(25,46),
            new KeyValuePair<int,int>(26,75),
            new KeyValuePair<int,int>(27,66),
            new KeyValuePair<int,int>(28,20),
        };

        public List<KeyValuePair<int, int>> Mark = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,45),
            new KeyValuePair<int,int>(2,28),
            new KeyValuePair<int,int>(3,35),
            new KeyValuePair<int,int>(4,41),
            new KeyValuePair<int,int>(5,43),
            new KeyValuePair<int,int>(6,56),
            new KeyValuePair<int,int>(7,37),
            new KeyValuePair<int,int>(8,38),
            new KeyValuePair<int,int>(9,50),
            new KeyValuePair<int,int>(10,52),
            new KeyValuePair<int,int>(11,33),
            new KeyValuePair<int,int>(12,44),
            new KeyValuePair<int,int>(13,37),
            new KeyValuePair<int,int>(14,72),
            new KeyValuePair<int,int>(15,47),
            new KeyValuePair<int,int>(16,20),
        };

        public List<KeyValuePair<int, int>> Luke = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,80),
            new KeyValuePair<int,int>(2,52),
            new KeyValuePair<int,int>(3,38),
            new KeyValuePair<int,int>(4,44),
            new KeyValuePair<int,int>(5,39),
            new KeyValuePair<int,int>(6,49),
            new KeyValuePair<int,int>(7,50),
            new KeyValuePair<int,int>(8,56),
            new KeyValuePair<int,int>(9,62),
            new KeyValuePair<int,int>(10,42),
            new KeyValuePair<int,int>(11,54),
            new KeyValuePair<int,int>(12,59),
            new KeyValuePair<int,int>(13,35),
            new KeyValuePair<int,int>(14,35),
            new KeyValuePair<int,int>(15,32),
            new KeyValuePair<int,int>(16,31),
            new KeyValuePair<int,int>(17,37),
            new KeyValuePair<int,int>(18,43),
            new KeyValuePair<int,int>(19,48),
            new KeyValuePair<int,int>(20,47),
            new KeyValuePair<int,int>(21,38),
            new KeyValuePair<int,int>(22,71),
            new KeyValuePair<int,int>(23,56),
            new KeyValuePair<int,int>(24,53),
        };

        public List<KeyValuePair<int, int>> John = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,51),
            new KeyValuePair<int,int>(2,25),
            new KeyValuePair<int,int>(3,36),
            new KeyValuePair<int,int>(4,54),
            new KeyValuePair<int,int>(5,47),
            new KeyValuePair<int,int>(6,71),
            new KeyValuePair<int,int>(7,53),
            new KeyValuePair<int,int>(8,59),
            new KeyValuePair<int,int>(9,41),
            new KeyValuePair<int,int>(10,42),
            new KeyValuePair<int,int>(11,57),
            new KeyValuePair<int,int>(12,50),
            new KeyValuePair<int,int>(13,38),
            new KeyValuePair<int,int>(14,31),
            new KeyValuePair<int,int>(15,27),
            new KeyValuePair<int,int>(16,33),
            new KeyValuePair<int,int>(17,26),
            new KeyValuePair<int,int>(18,40),
            new KeyValuePair<int,int>(19,42),
            new KeyValuePair<int,int>(20,31),
            new KeyValuePair<int,int>(21,25),
        };

        public List<KeyValuePair<int, int>> Acts = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,26),
            new KeyValuePair<int,int>(2,47),
            new KeyValuePair<int,int>(3,26),
            new KeyValuePair<int,int>(4,37),
            new KeyValuePair<int,int>(5,42),
            new KeyValuePair<int,int>(6,15),
            new KeyValuePair<int,int>(7,60),
            new KeyValuePair<int,int>(8,40),
            new KeyValuePair<int,int>(9,43),
            new KeyValuePair<int,int>(10,48),
            new KeyValuePair<int,int>(11,30),
            new KeyValuePair<int,int>(12,25),
            new KeyValuePair<int,int>(13,52),
            new KeyValuePair<int,int>(14,28),
            new KeyValuePair<int,int>(15,41),
            new KeyValuePair<int,int>(16,40),
            new KeyValuePair<int,int>(17,34),
            new KeyValuePair<int,int>(18,28),
            new KeyValuePair<int,int>(19,41),
            new KeyValuePair<int,int>(20,38),
            new KeyValuePair<int,int>(21,40),
            new KeyValuePair<int,int>(22,30),
            new KeyValuePair<int,int>(23,35),
            new KeyValuePair<int,int>(24,27),
            new KeyValuePair<int,int>(25,27),
            new KeyValuePair<int,int>(26,32),
            new KeyValuePair<int,int>(27,44),
            new KeyValuePair<int,int>(28,31),
        };

        public List<KeyValuePair<int, int>> Romans = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,32),
            new KeyValuePair<int,int>(2,29),
            new KeyValuePair<int,int>(3,31),
            new KeyValuePair<int,int>(4,25),
            new KeyValuePair<int,int>(5,21),
            new KeyValuePair<int,int>(6,23),
            new KeyValuePair<int,int>(7,25),
            new KeyValuePair<int,int>(8,39),
            new KeyValuePair<int,int>(9,33),
            new KeyValuePair<int,int>(10,21),
            new KeyValuePair<int,int>(11,36),
            new KeyValuePair<int,int>(12,21),
            new KeyValuePair<int,int>(13,14),
            new KeyValuePair<int,int>(14,23),
            new KeyValuePair<int,int>(15,33),
            new KeyValuePair<int,int>(16,27),
        };

        public List<KeyValuePair<int, int>> First_Corinthians = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,31),
            new KeyValuePair<int,int>(2,16),
            new KeyValuePair<int,int>(3,23),
            new KeyValuePair<int,int>(4,21),
            new KeyValuePair<int,int>(5,13),
            new KeyValuePair<int,int>(6,20),
            new KeyValuePair<int,int>(7,40),
            new KeyValuePair<int,int>(8,13),
            new KeyValuePair<int,int>(9,27),
            new KeyValuePair<int,int>(10,33),
            new KeyValuePair<int,int>(11,34),
            new KeyValuePair<int,int>(12,31),
            new KeyValuePair<int,int>(13,13),
            new KeyValuePair<int,int>(14,40),
            new KeyValuePair<int,int>(15,58),
            new KeyValuePair<int,int>(16,24),
        };

        public List<KeyValuePair<int, int>> Second_Corinthians = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,24),
            new KeyValuePair<int,int>(2,17),
            new KeyValuePair<int,int>(3,18),
            new KeyValuePair<int,int>(4,18),
            new KeyValuePair<int,int>(5,21),
            new KeyValuePair<int,int>(6,18),
            new KeyValuePair<int,int>(7,16),
            new KeyValuePair<int,int>(8,24),
            new KeyValuePair<int,int>(9,15),
            new KeyValuePair<int,int>(10,18),
            new KeyValuePair<int,int>(11,33),
            new KeyValuePair<int,int>(12,21),
            new KeyValuePair<int,int>(13,14),
        };

        public List<KeyValuePair<int, int>> Galatians = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,24),
            new KeyValuePair<int,int>(2,21),
            new KeyValuePair<int,int>(3,29),
            new KeyValuePair<int,int>(4,31),
            new KeyValuePair<int,int>(5,26),
            new KeyValuePair<int,int>(6,18),
        };

        public List<KeyValuePair<int, int>> Ephesians = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,23),
            new KeyValuePair<int,int>(2,22),
            new KeyValuePair<int,int>(3,21),
            new KeyValuePair<int,int>(4,32),
            new KeyValuePair<int,int>(5,33),
            new KeyValuePair<int,int>(6,24),
        };

        public List<KeyValuePair<int, int>> Philippians = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,30),
            new KeyValuePair<int,int>(2,30),
            new KeyValuePair<int,int>(3,21),
            new KeyValuePair<int,int>(4,23),
        };

        public List<KeyValuePair<int, int>> Colossians = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,29),
            new KeyValuePair<int,int>(2,23),
            new KeyValuePair<int,int>(3,25),
            new KeyValuePair<int,int>(4,18),
        };

        public List<KeyValuePair<int, int>> First_Thessalonians = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,10),
            new KeyValuePair<int,int>(2,20),
            new KeyValuePair<int,int>(3,13),
            new KeyValuePair<int,int>(4,18),
            new KeyValuePair<int,int>(5,28),
        };

        public List<KeyValuePair<int, int>> Second_Thessalonians = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,12),
            new KeyValuePair<int,int>(2,17),
            new KeyValuePair<int,int>(3,18),
        };

        public List<KeyValuePair<int, int>> First_Timothy = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,20),
            new KeyValuePair<int,int>(2,15),
            new KeyValuePair<int,int>(3,16),
            new KeyValuePair<int,int>(4,16),
            new KeyValuePair<int,int>(5,25),
            new KeyValuePair<int,int>(6,21),
        };

        public List<KeyValuePair<int, int>> Second_Timothy = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,18),
            new KeyValuePair<int,int>(2,26),
            new KeyValuePair<int,int>(3,17),
            new KeyValuePair<int,int>(4,22),
        };

        public List<KeyValuePair<int, int>> Titus = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,16),
            new KeyValuePair<int,int>(2,15),
            new KeyValuePair<int,int>(3,15),
        };

        public List<KeyValuePair<int, int>> Philemon = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,25),
        };

        public List<KeyValuePair<int, int>> Hebrews = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,14),
            new KeyValuePair<int,int>(2,18),
            new KeyValuePair<int,int>(3,19),
            new KeyValuePair<int,int>(4,16),
            new KeyValuePair<int,int>(5,14),
            new KeyValuePair<int,int>(6,20),
            new KeyValuePair<int,int>(7,28),
            new KeyValuePair<int,int>(8,13),
            new KeyValuePair<int,int>(9,28),
            new KeyValuePair<int,int>(10,39),
            new KeyValuePair<int,int>(11,40),
            new KeyValuePair<int,int>(12,29),
            new KeyValuePair<int,int>(13,25),
        };

        public List<KeyValuePair<int, int>> James = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,27),
            new KeyValuePair<int,int>(2,26),
            new KeyValuePair<int,int>(3,18),
            new KeyValuePair<int,int>(4,17),
            new KeyValuePair<int,int>(5,20),
        };

        public List<KeyValuePair<int, int>> First_Peter = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,25),
            new KeyValuePair<int,int>(2,25),
            new KeyValuePair<int,int>(3,22),
            new KeyValuePair<int,int>(4,19),
            new KeyValuePair<int,int>(5,14),
        };

        public List<KeyValuePair<int, int>> Second_Peter = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,21),
            new KeyValuePair<int,int>(2,22),
            new KeyValuePair<int,int>(3,18),
        };

        public List<KeyValuePair<int, int>> First_John = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,10),
            new KeyValuePair<int,int>(2,29),
            new KeyValuePair<int,int>(3,24),
            new KeyValuePair<int,int>(4,21),
            new KeyValuePair<int,int>(5,21),
        };

        public List<KeyValuePair<int, int>> Second_John = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,13),
        };

        public List<KeyValuePair<int, int>> Third_John = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,14),
        };

        public List<KeyValuePair<int, int>> Jude = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,25),
        };

        public List<KeyValuePair<int, int>> Revelation = new List<KeyValuePair<int, int>>
        {
            new KeyValuePair<int,int>(1,20),
            new KeyValuePair<int,int>(2,29),
            new KeyValuePair<int,int>(3,22),
            new KeyValuePair<int,int>(4,11),
            new KeyValuePair<int,int>(5,14),
            new KeyValuePair<int,int>(6,17),
            new KeyValuePair<int,int>(7,17),
            new KeyValuePair<int,int>(8,13),
            new KeyValuePair<int,int>(9,21),
            new KeyValuePair<int,int>(10,11),
            new KeyValuePair<int,int>(11,19),
            new KeyValuePair<int,int>(12,17),
            new KeyValuePair<int,int>(13,18),
            new KeyValuePair<int,int>(14,20),
            new KeyValuePair<int,int>(15,8),
            new KeyValuePair<int,int>(16,21),
            new KeyValuePair<int,int>(17,18),
            new KeyValuePair<int,int>(18,24),
            new KeyValuePair<int,int>(19,21),
            new KeyValuePair<int,int>(20,15),
            new KeyValuePair<int,int>(21,27),
            new KeyValuePair<int,int>(22,21),
        };
    }
}
